name: upsegmentation
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.3
  - pytorch=2.0.1
  - torchvision
  - tqdm
  - argh
  - pillow
  - svgutils
  - cairosvg
  - wandb
  - pip