name: upsegmentation
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - pytorch-cuda
  - torchvision
  - tqdm
  - argh
  - pillow
  - matplotlib
  - scikit-learn
  - svgutils
  - cairosvg
  - wandb
  - pip